### ISSUE TITLE
Valid Loss does not drop

### ISSUE THREAD

**Issue by yangz0626** [chenfengxu714/SqueezeSegV3#6]
Hi, I try to train the model using SSGV321.yaml but find the valid losses didn't drop, the value of valid loss is 0.8 in epoch 1 but 1.5 in epoch 100. However, the train loss, the valid IOU and the valid acc are all right. I don't know why.

**Comment by chenfengxu714** [comment]
Hi, we also find this issue during our training phase. It is indeed strange yet the valid IoU and acc are good. Although we have  tried to mitigate this issue by improving the models, adding regularizations and data augmentation etc, we still focused on the IoU and acc instead of the valid loss and didn't explore this issue further. However, I surely think this is an open issue that is worth exploring because we find a lower valid loss usually brings in the better IoU and acc. Thanks for your indicating it again, also hope your reply if you have any progress on this issue.
